[workspace]
members = [ "ic-memory-link",
    "icml",
]
resolver = "2"


[workspace.dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }
tempfile = "3.21.0"
ic-stable-structures = "0.7.0"

